language: php

sudo: false
dist: trusty

# Active PHP versions
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  #Â composer update should be required only for PHP 5.6 version
  include:
      - php: 5.6
        env: deps=update
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [ "$deps" == "update" ]; then composer update --prefer-dist; fi
  - if [ "$deps" != "update" ]; then composer install --prefer-dist; fi

script: vendor/bin/phpunit -c phpunit.xml.dist
